namespace ServerSleuth.Reporting.Export;

/// <summary>The outcome of exporting a whole <see cref="ReportBundle"/> — see skill.md
/// (Phase 9C) §4, §9, §11.</summary>
public sealed record ReportBundleExportResult
{
    public required ReportExportResult Json { get; init; }
    public required ReportExportResult Html { get; init; }

    /// <summary><c>null</c> unless manifest export was requested (skill.md §11: opt-in, not
    /// generated by default).</summary>
    public ReportExportResult? Manifest { get; init; }

    /// <summary><c>true</c> only when every requested artifact (JSON, HTML, and the manifest if
    /// requested) was actually written successfully.</summary>
    public bool Success => Json.Success && Html.Success && (Manifest is null || Manifest.Success);
}
