<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ServerSleuth.Analysis\ServerSleuth.Analysis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ServerSleuth.Reporting.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
